# Site settings
title: Younghwa Kang | 강영화
email: youngkang.design@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://youngkang.me" # the base hostname & protocol for your site
twitter_username: youngkang_UI
github_username:  young-hwa

# Build settings
markdown: kramdown

home_url: "http://youngkang.me"
representing_image: "/images/opengraph.png"